apiVersion: v1
kind: Service
metadata:
  name: votes-service-postgres-svc
spec:
  selector:
    app: votes-service-postgres-pod
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-service-postgres-deployment
spec:
  selector:
    matchLabels:
      app: votes-service-postgres-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: votes-service-postgres-pod
    spec:
      containers:
        - name: postgres
          image: "postgres:12.3"
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: votes-service-secrets
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: votes-service-secrets
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: votes-service-configmap
                  key: postgres_database
